### ISSUE TITLE
Support main programs with Docker

### ISSUE THREAD

**Issue by pzfreo** [ballerina-platform/module-ballerina-docker#403]
**Description:**
Docker should support main as well as service
For example it would be nice to package a TimerTask as a docker container. 

**Suggested Labels:**
Improvement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anuruddhal** [comment]
This is already supported. 
Check sample:
https://github.com/ballerina-platform/module-ballerina-docker/tree/master/samples/sample9

**Comment by pzfreo** [comment]
Thanks! I tried it and had some issues, but I guess that was my problem :-)
