### ISSUE TITLE
Using ballerina build fails with "Couldn't load native library"

### ISSUE THREAD

**Issue by shriharisc** [ballerina-platform/module-ballerina-docker#465]
I am trying to build a simple helloworld.bal using ballerina, but it fails at the docker stage with 

[root@cluster555-mixed-01 mywork]# ballerina build helloworld.bal
Compiling source
        helloworld.bal

Generating executables
        helloworld.jar

Generating artifacts...

        @kubernetes:Service                      - complete 1/1
        @kubernetes:Deployment                   - complete 1/1
error [k8s plugin]: module [.] unable to build docker image:  Couldn't load native library

**Comment by anuruddhal** [comment]
what is the Ballerina version you are using? Have you installed Docker in the host machine?
